# Generated by Django 4.2.6 on 2023-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.IntegerField()),
                ('developer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('RealaseDate', models.DateField()),
                ('RequiredAge', models.IntegerField()),
                ('Price', models.FloatField()),
                ('AboutTheGame', models.TextField()),
                ('SupportedLanguages', models.TextField()),
                ('HeaderImage', models.URLField()),
                ('Windows', models.BooleanField()),
                ('Mac', models.BooleanField()),
                ('Linux', models.BooleanField()),
                ('MetacriticScore', models.IntegerField()),
                ('Positive', models.IntegerField()),
                ('Negative', models.IntegerField()),
                ('Categories', models.TextField()),
                ('Genres', models.TextField()),
                ('Tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.IntegerField()),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
