# Generated by Django 4.2.6 on 2023-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, default=None, max_length=260, null=True)),
                ('developer', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('app_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=210, null=True)),
                ('release_date', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('required_age', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('about_the_game', models.TextField(blank=True, default=None, null=True)),
                ('supported_languages', models.TextField(blank=True, default=None, null=True)),
                ('header_image', models.URLField(blank=True, default=None, null=True)),
                ('windows', models.BooleanField(blank=True, default=False, null=True)),
                ('mac', models.BooleanField(blank=True, default=False, null=True)),
                ('linux', models.BooleanField(blank=True, default=False, null=True)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('positive', models.IntegerField(blank=True, default=0, null=True)),
                ('negative', models.IntegerField(blank=True, default=0, null=True)),
                ('categories', models.TextField(blank=True, default=None, null=True)),
                ('genres', models.TextField(blank=True, default=None, null=True)),
                ('tags', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, default=None, max_length=260, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Disliked',
            fields=[
                ('app_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('header_image', models.URLField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Games',
            fields=[
                ('app_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('header_image', models.URLField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, default=None, max_length=260, null=True)),
                ('publisher', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resulting_Games',
            fields=[
                ('app_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('header_image', models.URLField(blank=True, default=None, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
