# Generated by Django 4.2.6 on 2023-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='AboutTheGame',
            new_name='about_the_game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Genres',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='HeaderImage',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Linux',
            new_name='linux',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Mac',
            new_name='mac',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='AppID',
            new_name='metacritic_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='RealaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='MetacriticScore',
            new_name='required_age',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='SupportedLanguages',
            new_name='supported_languages',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Windows',
            new_name='windows',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='AppID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='RequiredAge',
        ),
        migrations.RemoveField(
            model_name='language',
            name='AppID',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='AppID',
        ),
        migrations.AddField(
            model_name='developer',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
