# Generated by Django 4.2.6 on 2023-11-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_aboutthegame_game_about_the_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Negative',
            new_name='negative',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Positive',
            new_name='positive',
        ),
    ]
