# Generated by Django 4.2.6 on 2023-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_game_metacritic_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=200),
        ),
    ]
