# Generated by Django 4.2.6 on 2023-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='linux',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
