# Generated by Django 4.2.6 on 2023-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_game_about_the_game_alter_game_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
