# Generated by Django 4.2.6 on 2023-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_game_id_alter_developer_app_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='app_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
