# Generated by Django 4.2.6 on 2023-11-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_alter_developer_app_id_alter_publisher_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Disliked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('title', 'action')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='liked_disliked',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='frontend.liked_disliked'),
        ),
    ]
