# Generated by Django 4.2.6 on 2023-11-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_liked_disliked_game_liked_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='liked_disliked',
        ),
    ]
