# Generated by Django 4.2.6 on 2023-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_remove_developer_app_id_remove_language_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, to='frontend.developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='frontend.publisher'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='supported_languages',
        ),
        migrations.AddField(
            model_name='game',
            name='supported_languages',
            field=models.ManyToManyField(blank=True, to='frontend.language'),
        ),
    ]
